1111                            111111
111111117                       123
2                               2222222
3333333                         CMAKE
CMakeLists.txt                  Makefile
a                               b
cmake-build-debug               fffile
fuck                            fuckfuck
fuckfuckfuck                    g
hh                              inc
itoa.c                          libmx
libmx.a                         link
lll                             main.c
mx_cols_and_rows.c              mx_data_init.c
mx_dir_parse.c                  mx_errors_array.c
mx_files_count.c                mx_find_name_len.c
mx_get_bsize_num.c              mx_get_inode_num.c
mx_get_path.c                   mx_get_win_size.c
mx_getstats.c                   mx_output_1.c
mx_output_c.c                   mx_output_file.c
mx_output_file_x.c              mx_output_l.c
mx_output_m.c                   mx_output_x.c
mx_parse_args.c                 mx_print_colored.c
mx_print_dirs.c                 mx_print_err.c
mx_print_error.c                mx_print_errors.c
mx_print_files.c                mx_print_is.c
mx_print_link.c                 mx_print_spaces.c
mx_print_total.c                mx_printchar.c
mx_printer.c                    mx_printstr.c
mx_prior_all.c                  mx_quick_cmp_sort.c
mx_quick_elem_sort.c            mx_quick_rev_elem_sort.c
mx_quick_rev_size_sort.c        mx_quick_rev_time_sort.c
mx_quick_size_sort.c            mx_quick_time_sort.c
mx_quicksort.c                  mx_read_data.c
mx_read_dir.c                   mx_read_flags.c
mx_set_bsize.c                  mx_set_mode.c
mx_set_stats.c                  mx_set_time.c
mx_setgrp.c                     mx_setuser.c
mx_sorting.c                    mx_strcmp.c
mx_strcpy.c                     mx_strdup.c
mx_strjoin.c                    mx_strlen.c
mx_strncpy.c                    mx_strndup.c
mx_strnew.c                     mx_switch_flags.c
mx_uls.c                        num
obj                             output
src                             target
test_emptyyyy                   test_uls1
test_uls2                       tgs.txt
tmp.c                           tou
uls                             uls.h
uuu                             yyy
